### ISSUE TITLE
always an error

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [LXGaming/UnitySkin#1]
I am trying to use your tool like this 

```
java -jar UnitySkin-1.2.6,jar
...
Enter Path to Unity Binary: 
C:\Program Files\Unity\Hub\Editor\2021.3.16f1\Editor\Unity.exe
```

it fails with `EOFException` on performing `UnitySkin.prepare()` method

Any suggestions please?

**Comment by LXGaming** [comment]
I haven't bothered maintaining this project as I stopped using Unity, `2021.3.16f1` is not supported.

According to [Unity Support](https://support.unity.com/hc/en-us/articles/115004982743-How-can-I-change-my-Editor-theme-) "As of Unity 2019.4.8, the Dark Editor theme is available to both paid subscribers and free users alike.".

**Comment by dmitrykolesnikovich** [comment]
Thanks I will try 2019 version

**Comment by LXGaming** [comment]
The Unity Support post indicates that you should be able to enable Dark Theme with the version you're currently using, you shouldn't need to downgrade.

**Comment by dmitrykolesnikovich** [comment]
My real intent is to replicate unity style in my javafx app.

**Comment by LXGaming** [comment]
Ok, I don't believe UnitySkin is applicable, its only purpose is to enable the dark theme in legacy Unity versions where it was behind a pay wall, You can use Unity 2019.4.8 or higher to access the dark theme and replicate the theme / style from Unity directly.
